server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8001
    #context-path: /platform-app
# DataSource
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://2.1.1.1:3306/kitty?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=UTC
      password: mszq@-pl,mko0
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  # spring boot app
  application:
    name: platform-app
  activiti:
    check-processes-definitions: true
    database-schema-update: true
    async-executor-activate: false
    process-definition-location-prefix: classpath:/processes/
    process-definition-location-suffixes:
      -*.bpmn
      -*.bpm20.xml
    history-level: full
    

#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        serviceName: ${spring.application.name}	# 注册到consul的服务名称
#  boot:
#    app:
#      client:
#        url: "http://localhost:8000"
# 开放健康检查接口
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
# pagehelper   
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  config: classpath:log4j2.yml

    